name: Update Required Status Check
description: Update Required Status Check according to the workflow run's conclusion
branding:
  icon: git-commit
  color: blue
inputs:
  github_token:
    description: |
      A GitHub Access Token. The permission statuses:write is required.
    required: false
    default: ${{ github.token }}
  context:
    description: |
      A commit status's context.
    required: false
    default: status-check
  description:
    description: |
      A commit status's description.
    required: false
    default: ""
runs:
  using: composite
  steps:
    - shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        SHA: ${{ github.event.workflow_run.head_sha }}
        CONCLUSION: ${{ github.event.workflow_run.conclusion }}
        CONTEXT: ${{ inputs.context }}
        DESCRIPTION: ${{ inputs.description }}
      run: |
        # state: error, failure, pending, success
        # conclusion: action_required, cancelled, failure, neutral, skipped, stale, success, timed_out, startup_failure, null
        state=success
        if [ "$CONCLUSION" != success ]; then
          state=failure
        fi
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/$GITHUB_REPOSITORY/statuses/$SHA" \
          -f "state=$state" \
          -f "target_url=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" \
          -f "description=$DESCRIPTION" \
          -f "context=$CONTEXT"
